// ===== Shared dataset for the unified Star Wars audiobook library =====
const CDN = "https://static.wikia.nocookie.net/starwars/images/";

// Era metadata for the landing grid. `key` maps into BOOKS below.
const ERAS = [
  { key:null, no:"Era I", name:"Dawn of the Jedi", yrs:"~25,000 BBY", desc:"No canon audiobooks yet.", empty:true },
  { key:null, no:"Era II", name:"The Old Republic", yrs:"~5000–1000 BBY", desc:"No canon audiobooks yet.", empty:true },
  { key:"high-republic", no:"Era III", name:"The High Republic", yrs:"c. 382–228 BBY", desc:"The golden age of the Jedi — the largest single block of modern audiobooks.",
    sub:"The golden age of the Jedi (c. 500–100 BBY) — every adult, young-adult, and junior novel plus the full-cast audio dramas, in in-universe order.",
    band:"Era III of IX · Canon continuity", filters:["Adult","YA","Junior","Audio Drama"], accent:"gold" },
  { key:"fall-of-the-jedi", no:"Era IV", name:"Fall of the Jedi", yrs:"41–19 BBY", desc:"The prequels and Clone Wars — the slow corruption of the Republic.",
    sub:"The prequel and Clone Wars window (41–19 BBY) — the slow corruption of the Republic and the fall of the Jedi Order.",
    band:"Era IV of IX · Canon continuity", filters:["Adult","YA","Audio Drama"], accent:"gold" },
  { key:"reign-of-the-empire", no:"Era V", name:"Reign of the Empire", yrs:"19–1 BBY", desc:"The Empire consolidates power; the Thrawn and Ascendancy saga.",
    sub:"The Empire consolidates power and the seeds of the Rebellion are planted (19–1 BBY). Dominated by the Thrawn and Ascendancy titles.",
    band:"Era V of IX · Canon continuity", filters:["Adult","YA"], accent:"gold" },
  { key:"age-of-rebellion", no:"Era VI", name:"Age of Rebellion", yrs:"0 BBY–4 ABY", desc:"The original-trilogy window, from the Death Star to Jakku's eve.",
    sub:"The original-trilogy window (0 BBY–4 ABY) — the Rebellion answers the Empire at its height, from the Death Star to the eve of Jakku.",
    band:"Era VI of IX · Canon continuity", filters:["Adult","YA","Anthology"], accent:"gold" },
  { key:"new-republic", no:"Era VII", name:"The New Republic", yrs:"4–21 ABY", desc:"After Endor — the Aftermath trilogy and the Mandalorian era.",
    sub:"After Endor (4–~21 ABY) — the fall of the Empire at Jakku, the mercenary and Chiss stories, and the Mandalorian streaming era.",
    band:"Era VII of IX · Canon continuity", filters:["Adult","YA"], accent:"gold" },
  { key:"rise-first-order", no:"Era VIII", name:"Rise of the First Order", yrs:"c. 28–33 ABY", desc:"The bridge to the sequel trilogy as the First Order rebuilds in secret.",
    sub:"The bridge to the sequel trilogy (c. 28–33 ABY) — the New Republic drifts as the First Order rebuilds Imperial power in secret.",
    band:"Era VIII of IX · Canon continuity", filters:["Adult","YA"], accent:"gold" },
  { key:"new-jedi-order", no:"Era IX", name:"New Jedi Order", yrs:"34–35 ABY", desc:"The sequel-trilogy window — the Resistance and the stand at Exegol.",
    sub:"The sequel-trilogy window (34–35 ABY) — the Resistance against the First Order, then the final stand at Exegol.",
    band:"Era IX of IX · Canon continuity", filters:["Adult","YA","Anthology"], accent:"gold" }
];

const LEGENDS_ERA = { key:"legends", no:"Legends", name:"Expanded Universe", yrs:"25,793 BBY – onward",
  desc:"The pre-2014 continuity: Darth Bane, Darth Plagueis, Kenobi, the Old Republic games, and more.",
  sub:"The pre-2014 Expanded Universe, rebranded \"Legends\" — a separate continuity from Canon. Many began as abridged recordings; Del Rey has since re-recorded flagship titles unabridged. Placement uses the older Legends era names.",
  band:"Separate continuity · not Canon", filters:["Unabridged","Audio Drama"], accent:"purple" };

const BOOKS = {
  "high-republic": [
    { phase:"Phase II — Quest of the Jedi", cat:"YA", title:"Path of Deceit", author:"Gratton & Ireland", narrator:"Erin Yvette", pubdate:"October 4, 2022", publisher:"Disney–Lucasfilm Press", timeline:"382 BBY", runtime:"8h 10m", cover:CDN+"3/38/TheHighRepublic-PathOfDeceit.jpg/revision/latest?cb=20220526233239", lead:"An era of change brings new hopes and possibilities — but also new dangers.", summary:"On the Outer Rim world of Dalna, Jedi Zallah Macri and her Padawan Kevmo Zink investigate the Path of the Open Hand, who believe the Force must not be used by anyone. Believer Marda Ro and Kevmo feel an instant connection — until she learns he's a Jedi. But the Path's leader, the Mother, has an agenda that can never coexist peacefully with the Jedi." },
    { phase:"Phase II — Quest of the Jedi", cat:"Junior", title:"Quest for the Hidden City", author:"George Mann", narrator:"Subhadra Newton", pubdate:"November 1, 2022", publisher:"Disney–Lucasfilm Press", timeline:"382 BBY", runtime:"5h 47m", cover:CDN+"4/4b/QuestfortheHiddenCity-cover.jpg/revision/latest?cb=20240109054813", lead:"An age of exploration in a galaxy far, far away.", summary:"When a Pathfinder team's droid is found drifting bearing a cryptic message, Jedi Knight Silandra Sho and her Padawan Rooper Nitani are sent to find the missing team. Their investigation leads to Gloam, a ravaged world said to be haunted by monsters — with answers hidden in a city beneath the surface." },
    { phase:"Phase II — Quest of the Jedi", cat:"Adult", title:"Convergence", author:"Zoraida Córdova", narrator:"Marc Thompson", pubdate:"November 22, 2022", publisher:"Del Rey", timeline:"382 BBY", runtime:"13h 28m", cover:CDN+"f/f4/HighRepublicConvergence-Cover.jpg/revision/latest?cb=20220620193112", lead:"A story set generations before Light of the Jedi.", summary:"On the close-orbiting planets of Eiram and E'ronoh, a half-decade of war threatens surrounding systems. The last hope for peace is a royal marriage — but an assassination attempt tilts the worlds back into all-out conflict. Jedi Gella Nattai volunteers to uncover the culprit, alongside the chancellor's privileged son Axel Greylark." },
    { phase:"Phase II — Quest of the Jedi", cat:"Audio Drama", title:"The Battle of Jedha", author:"George Mann", narrator:"Full cast", pubdate:"January 3, 2023", publisher:"Random House Audio", timeline:"382 BBY", runtime:"5h 27m", cover:CDN+"8/88/Battle-Jedha-Final.jpg/revision/latest?cb=20220723005621", lead:"An audio-original drama, told entirely through full-cast performance.", summary:"On the holy moon of Jedha, two Jedi Knights work to negotiate a truce between warring factions as the Path of the Open Hand stokes chaos. The first High Republic audio drama since Tempest Runner, dramatizing the pivotal battle that echoes across Phase II." },
    { phase:"Phase II — Quest of the Jedi", cat:"Junior", title:"Quest for Planet X", author:"Tessa Gratton", narrator:"Amber Lee Connors", pubdate:"April 4, 2023", publisher:"Disney–Lucasfilm Press", timeline:"382 BBY", runtime:"5h 26m", cover:CDN+"9/94/QuestForPlanetX.jpg/revision/latest?cb=20230418030609", lead:"The young Pathfinders press deeper into the unknown frontier.", summary:"Rooper Nitani and Dass Leffbruk join a perilous expedition toward the mysterious Planet X, racing the Path of the Open Hand to a world that holds the secret of the deadly creatures the Mother intends to unleash on the galaxy." },
    { phase:"Phase II — Quest of the Jedi", cat:"YA", title:"Path of Vengeance", author:"Cavan Scott", narrator:"Emily O'Brien", pubdate:"May 2, 2023", publisher:"Disney–Lucasfilm Press", timeline:"382 BBY", runtime:"11h 59m", cover:CDN+"2/2a/TheHighRepublic-PathofVengeance-cover.jpg/revision/latest?cb=20221010031440", lead:"Cousins Marda and Yana Ro — bound by blood but driven apart by faith.", summary:"Both belong to the Path of the Open Hand. While Marda joins a perilous expedition to Planet X in search of more creatures to use against the Jedi, Yana forms an unexpected alliance to wrest the Path from the Mother's control. These two young women face a crossroads that will decide the galaxy's fate." },
    { phase:"Phase II — Quest of the Jedi", cat:"Adult", title:"Cataclysm", author:"Lydia Kang", narrator:"Marc Thompson", pubdate:"April 4, 2023", publisher:"Random House Worlds", timeline:"382 BBY", runtime:"16h 19m", cover:CDN+"2/2b/TheHighRepublic-Cataclysm-cover.jpg/revision/latest?cb=20221018054601", lead:"The Jedi race to confront the Path of the Open Hand and end the Forever War.", summary:"After a disaster at the treaty signing on Jedha reignites violence between Eiram and E'ronoh, all signs point to the Path of the Open Hand. Jedi Gella Nattai turns to the one person she believes can unravel the mystery but the last she wants to trust: the imprisoned Axel Greylark. All roads lead to Dalna." },
    { phase:"Phase I — Light of the Jedi", cat:"YA", title:"Into the Dark", author:"Claudia Gray", narrator:"Dan Bittner", pubdate:"February 2, 2021", publisher:"Disney–Lucasfilm Press", timeline:"232 BBY", runtime:"11h 11m", cover:CDN+"8/81/Into_the_Dark_cover.jpg/revision/latest?cb=20200225074008", lead:"Not everyone who hears the call to adventure wants to answer it.", summary:"Padawan Reath Silas would rather stay in the Jedi Archives than head for the frontier. But when his ship is knocked out of hyperspace by a galaxy-wide disaster, the Jedi take refuge on a seemingly abandoned space station — where strange things start happening, and a truth surfaces that could end in tragedy." },
    { phase:"Phase I — Light of the Jedi", cat:"Adult", title:"Light of the Jedi", author:"Charles Soule", narrator:"Marc Thompson", pubdate:"January 5, 2021", publisher:"Del Rey", timeline:"232 BBY", runtime:"13h 35m", cover:CDN+"e/e2/Light_of_the_Jedi_cover.jpg/revision/latest?cb=20200225020702", lead:"Long before the First Order, before the Empire, before even The Phantom Menace… Jedi lit the way for the galaxy.", summary:"It is a golden age. But when a catastrophe in hyperspace tears a ship to pieces, the shrapnel threatens an entire system. The Jedi race to the scene — but the disaster is far more sinister than they suspect, and a threat hides in the darkness beyond the light of the age: the marauders known as the Nihil." },
    { phase:"Phase I — Light of the Jedi", cat:"Junior", title:"A Test of Courage", author:"Justina Ireland", narrator:"Keylor Leigh", pubdate:"January 5, 2021", publisher:"Disney–Lucasfilm Press", timeline:"232 BBY", runtime:"4h 34m", cover:CDN+"c/c5/THR-ATestofCourage.jpg/revision/latest?cb=20200323221151", lead:"The Jedi lit the way for the galaxy in a golden age known as the High Republic.", summary:"Newly knighted at sixteen, Vernestra Rwoh is charged with supervising a young inventor on a cruiser bound for Starlight Beacon. When bombs go off aboard the ship, Vernestra, the inventor, a Jedi Padawan, and an ambassador's son escape to a nearby jungle moon — where danger lurks in the forest." },
    { phase:"Phase I — Light of the Jedi", cat:"Adult", title:"The Rising Storm", author:"Cavan Scott", narrator:"Marc Thompson", pubdate:"June 29, 2021", publisher:"Del Rey", timeline:"231 BBY", runtime:"15h 32m", cover:CDN+"c/c8/TheHighRepublic-TheRisingStorm.jpg/revision/latest?cb=20210120060833", lead:"The heroes of the High Republic return to face a shattered peace and a fearsome foe.", summary:"Chancellor Lina Soh plans the Republic Fair — a showcase of the expanding Republic's peace. But as the eyes of the galaxy turn toward the Fair, so does the fury of the Nihil. Marchion Ro descends on the celebration, and the Jedi come face to face with the true fear he plans to unleash — the kind even the Force cannot shield them from." },
    { phase:"Phase I — Light of the Jedi", cat:"Junior", title:"Race to Crashpoint Tower", author:"Daniel José Older", narrator:"Todd Haberkorn", pubdate:"June 29, 2021", publisher:"Disney–Lucasfilm Press", timeline:"231 BBY", runtime:"3h 20m", cover:CDN+"6/69/Race_to_Crashpoint_Tower_final_cover.jpg/revision/latest?cb=20210215210659", lead:"The Republic Fair is coming — and so is disaster.", summary:"As Valo prepares for the fair, Jedi Padawan Ram Jomaram discovers that someone has disabled the planet's communications tower — a sign that Valo, and the fair, are in danger. When the Nihil launch a surprise attack, it's up to Ram to face down the enemy at Crashpoint Tower and call for help." },
    { phase:"Phase I — Light of the Jedi", cat:"YA", title:"Out of the Shadows", author:"Justina Ireland", narrator:"Keylor Leigh", pubdate:"July 27, 2021", publisher:"Disney–Lucasfilm Press", timeline:"231 BBY", runtime:"10h 50m", cover:CDN+"5/51/Star_Wars_The_High_Republic_Out_of_the_Shadows_final_cover.jpg/revision/latest?cb=20210217035059", lead:"The darkest secrets are the hardest to bring to light.", summary:"Sylvestri Yarrow fights to keep her family cargo business alive amid Nihil attacks. On Coruscant she's drawn into a feud between two powerful families over a patch of frontier space. Meanwhile Jedi Vernestra Rwoh is summoned to help with the same dispute — and the answer takes Syl back to her past." },
    { phase:"Phase I — Light of the Jedi", cat:"Audio Drama", title:"Tempest Runner", author:"Cavan Scott", narrator:"Full cast", pubdate:"August 31, 2021", publisher:"Random House Audio", timeline:"231 BBY", runtime:"6h 05m", cover:CDN+"f/ff/The_High_Republic_Tempest_Runner_final_cover.jpg/revision/latest?cb=20210630050619", lead:"An audio-original drama centered on one of the Nihil's most ruthless leaders.", summary:"Tempest Runner Lourna Dee has evaded the Jedi for years. When she is finally captured and imprisoned, she must scheme her way to freedom — a full-cast drama digging into the ambition and survival instinct of one of the Nihil's most dangerous figures." },
    { phase:"Phase I — Light of the Jedi", cat:"Junior", title:"Mission to Disaster", author:"Justina Ireland", narrator:"Keylor Leigh", pubdate:"January 4, 2022", publisher:"Disney–Lucasfilm Press", timeline:"230 BBY", runtime:"5h 06m", cover:CDN+"8/82/The_High_Republic_Mission_to_Disaster_audiobook.png/revision/latest?cb=20220104183219", lead:"Vernestra and Avon face the Nihil's growing shadow.", summary:"After the disaster at the Republic Fair, Jedi Knight Vernestra Rwoh and young Avon Starros are pulled into a dangerous confrontation with the Nihil when Avon is kidnapped — forcing Vernestra to mount a rescue against a rising storm." },
    { phase:"Phase I — Light of the Jedi", cat:"Adult", title:"The Fallen Star", author:"Claudia Gray", narrator:"Marc Thompson", pubdate:"January 4, 2022", publisher:"Random House Worlds", timeline:"230 BBY", runtime:"13h 30m", cover:CDN+"7/79/HighRepublicTheFallenStar-Cover.jpg/revision/latest?cb=20210915222426", lead:"The light of the Jedi faces its darkest hour.", summary:"Hanging like a jewel in the Outer Rim, the Starlight Beacon embodies the High Republic at its apex. As refugees flee the Nihil's attacks, the Beacon stands ready to shelter and heal. But the storm the Jedi thought had passed still rages; Marchion Ro is preparing his most daring attack yet — one designed to snuff out the light of the Jedi." },
    { phase:"Phase I — Light of the Jedi", cat:"YA", title:"Midnight Horizon", author:"Daniel José Older", narrator:"Todd Haberkorn", pubdate:"February 1, 2022", publisher:"Disney–Lucasfilm Press", timeline:"230 BBY", runtime:"10h 05m", cover:CDN+"d/dc/HighRepublicMidnightHorizon.jpg/revision/latest?cb=20210916182836", lead:"The Nihil strike at the heart of the Galactic Core.", summary:"Word comes of a suspected Nihil attack on cosmopolitan Corellia. Jedi Masters Cohmac Vitus and Kantam Sy, with Padawans Reath Silas and Ram Jomaram, go undercover with a brazen young security specialist named Crash — only to uncover one part of a greater plan that could lead the Jedi to their most stunning defeat yet." },
    { phase:"Phase III — Trials of the Jedi", cat:"Adult", title:"The Eye of Darkness", author:"George Mann", narrator:"Marc Thompson", pubdate:"November 14, 2023", publisher:"Random House Worlds", timeline:"229–228 BBY", runtime:"15h 22m", cover:CDN+"b/b0/TheHighRepublic-TheEyeofDarkness-cover.jpg/revision/latest?cb=20230705195428", lead:"One year after The Fallen Star, the Jedi fight to break the Nihil's control over the galaxy.", summary:"Following the destruction of Starlight Beacon, the Nihil establish an impenetrable barrier — the Stormwall — around part of the Outer Rim, where Marchion Ro rules. Jedi trapped behind enemy lines, including Avar Kriss, fight to help pillaged worlds while Elzar Mann and Bell Zettifar work to breach the wall." },
    { phase:"Phase III — Trials of the Jedi", cat:"YA", title:"Defy the Storm", author:"Gratton & Ireland", narrator:"Amber Lee Connors", pubdate:"March 5, 2024", publisher:"Disney–Lucasfilm Press", timeline:"228 BBY", runtime:"10h 48m", cover:"https://static.wikia.nocookie.net/starwars/images/0/09/DtS-AB-Cover.png/revision/latest?cb=20240318145546", lead:"A desperate mission behind the Stormwall.", summary:"With the galaxy divided by the Nihil's Occlusion Zone, a group of young Jedi mount a daring mission to breach the Stormwall and strike back — even as the Nameless creatures make every Jedi's connection to the Force a liability. (Publisher summary abbreviated.)" },
    { phase:"Phase III — Trials of the Jedi", cat:"Adult", title:"Temptation of the Force", author:"Tessa Gratton", narrator:"Marc Thompson", pubdate:"June 11, 2024", publisher:"Random House Worlds", timeline:"228 BBY", runtime:"17h 03m", cover:"https://starwars.fandom.com/wiki/Special:FilePath/TheHighRepublic-TemptationoftheForce-cover.jpg", lead:"The penultimate adult novel of the High Republic.", summary:"As the Nihil's Stormwall continues to divide the galaxy, the Jedi press their fight to bring down the Occlusion Zone. Avar Kriss and Elzar Mann's paths converge again amid mounting losses, and the Jedi edge closer to a reckoning with the Nameless — the Force-eating creatures at the heart of Ro's power. (Publisher summary abbreviated.)" },
    { phase:"Phase III — Trials of the Jedi", cat:"YA", title:"Into the Light", author:"Claudia Gray", narrator:"Amber Lee Connors", pubdate:"April 15, 2025", publisher:"Disney–Lucasfilm Press", timeline:"228 BBY", runtime:"9h 57m", cover:"https://starwars.fandom.com/wiki/Special:FilePath/TheHighRepublic-IntotheLight-cover.jpg", lead:"The young Jedi make their stand as the era nears its end.", summary:"As the Nihil's grip finally begins to crack, Reath Silas and the next generation of Jedi confront the cost of the war and the lingering threat of the Nameless. (Publisher summary abbreviated.)" },
    { phase:"Phase III — Trials of the Jedi", cat:"Audio Drama", title:"Tempest Breaker", author:"Cavan Scott", narrator:"Full cast", pubdate:"December 3, 2024", publisher:"Random House Audio", timeline:"228 BBY", runtime:"6h 07m", cover:"https://starwars.fandom.com/wiki/Special:FilePath/TB-AB-Cover.png", lead:"The final full-cast High Republic audio drama.", summary:"Lourna Dee's story reaches its climax in this audio-original drama, as the Nihil's fortunes turn and old scores come due behind the Stormwall. (Publisher summary abbreviated.)" },
    { phase:"Phase III — Trials of the Jedi", cat:"Adult", title:"Trials of the Jedi", author:"Charles Soule", narrator:"Marc Thompson", pubdate:"June 17, 2025", publisher:"Random House Worlds", timeline:"228 BBY", runtime:"17h 58m", cover:"https://starwars.fandom.com/wiki/Special:FilePath/TheHighRepublic-TrialsoftheJedi-Cover.png", lead:"The climactic finale of the entire High Republic publishing initiative.", summary:"Charles Soule, who launched the era with Light of the Jedi, closes it here. The Jedi make their final stand against Marchion Ro and the Nihil as the fate of the Occlusion Zone — and the golden age itself — is decided. (Publisher summary abbreviated.)" },
    { phase:"The Acolyte tie-ins (late High Republic)", cat:"Adult", title:"The Acolyte: Wayseeker", author:"Justina Ireland", narrator:"Jessica Almasy", pubdate:"May 6, 2025", publisher:"Random House Worlds", timeline:"c. 160 BBY", runtime:"9h 10m", cover:"https://starwars.fandom.com/wiki/Special:FilePath/TheAcolyte-Wayseeker-cover3.jpg", lead:"A tie-in to the Disney+ series The Acolyte, set in the era's twilight.", summary:"Long after the Nihil war, a Wayseeker Jedi who operates outside the Council's authority follows the will of the Force to the galaxy's fringes — bridging the classic High Republic and the late-era world of The Acolyte. (Publisher summary abbreviated.)" },
    { phase:"The Acolyte tie-ins (late High Republic)", cat:"YA", title:"The Acolyte: The Crystal Crown", author:"Tessa Gratton", narrator:"Kristen DiMercurio", pubdate:"October 28, 2025", publisher:"Disney–Lucasfilm Press", timeline:"134 BBY", runtime:"10h 23m", cover:"https://starwars.fandom.com/wiki/Special:FilePath/TheAcolyte-TheCrystalCrown-Cover.jpg", lead:"Set in the immediate world of The Acolyte.", summary:"A young-adult story set in the years of the Disney+ series, following Jedi close to the events that would spark the Order's hidden crisis. (Publisher summary abbreviated.)" }
  ],

  "fall-of-the-jedi": [
    { phase:"Before the Clone Wars", cat:"YA", title:"Padawan", author:"Kiersten White", narrator:"Gary Furlong", pubdate:"July 26, 2022", publisher:"Disney–Lucasfilm Press", timeline:"41 BBY", runtime:"7h 26m", cover:CDN+"7/74/Padawan_cover.jpg/revision/latest?cb=20220225073815", lead:"Being a teenager is hard enough without also training to be a Jedi.", summary:"Newly apprenticed to Qui-Gon Jinn, Obi-Wan chafes at his master's meditation-heavy training. When Qui-Gon vanishes before a mission, an angry Obi-Wan sets out alone and finds a pack of feral, Force-wielding teens on a mysterious planet — and a nagging sense that something is deeply wrong with the Force there." },
    { phase:"Before the Clone Wars", cat:"Adult", title:"Master & Apprentice", author:"Claudia Gray", narrator:"Jonathan Davis", pubdate:"April 16, 2019", publisher:"Del Rey", timeline:"40 BBY", runtime:"11h 42m", cover:CDN+"c/c5/MasterApprentice-Hardcover.jpg/revision/latest?cb=20181007232310", lead:"An unexpected offer threatens the bond between Qui-Gon Jinn and Obi-Wan Kenobi.", summary:"When Qui-Gon is invited to join the Jedi Council — which would end his partnership with Obi-Wan — the two struggle to understand each other. A mission to the royal court of Pijal becomes clouded by deceit and by visions of disaster that take hold in Qui-Gon's mind, testing Obi-Wan's faith in his master." },
    { phase:"Before the Clone Wars", cat:"Adult", title:"The Living Force", author:"John Jackson Miller", narrator:"Marc Thompson", pubdate:"April 9, 2024", publisher:"Random House Worlds", timeline:"33 BBY", runtime:"16h 10m", cover:CDN+"9/91/TheLivingForce.png/revision/latest?cb=20230907175537", lead:"In the year before The Phantom Menace, the entire Jedi Council confronts a galaxy on the brink of change.", summary:"As a Jedi outpost is set to be decommissioned on Kwenn, Qui-Gon Jinn challenges the Council about the Order's growing isolation. Mace Windu's bold response: all twelve Jedi Masters embark on a goodwill mission. But warring pirate factions unite to assassinate the Council." },
    { phase:"Before the Clone Wars", cat:"YA", title:"Queen's Peril", author:"E. K. Johnston", narrator:"Catherine Taber", pubdate:"June 2, 2020", publisher:"Disney–Lucasfilm Press", timeline:"32 BBY", runtime:"6h 10m", cover:CDN+"f/fb/Queens_Peril_audiobook_cover.png/revision/latest?cb=20201011014308", lead:"Padmé Naberrie wins the election for Queen of Naboo — and assembles her handmaidens.", summary:"Fourteen-year-old Padmé takes the name Amidala and, with security advisor Captain Panaka, recruits handmaidens to serve as her aides, confidants, protectors, and decoys. As the young women learn to work together, their peaceful world is invaded by the Trade Federation." },
    { phase:"Before the Clone Wars", cat:"Adult", title:"Mace Windu: The Glass Abyss", author:"Steven Barnes", narrator:"William DeMeritt", pubdate:"October 15, 2024", publisher:"Random House Worlds", timeline:"c. 32 BBY", runtime:"11h 39m", cover:CDN+"9/9a/MaceWinduTheGlassAbyss-revealcover.jpg/revision/latest?cb=20231208144754", lead:"Mace Windu travels to a dangerous, remote planet to fulfill Qui-Gon's last request.", summary:"Reeling from Qui-Gon's death, Mace receives a posthumous message: a plea to help the Outer Rim planet Metagos, its surface turned to irradiated glass, its survivors living underground under warring crime lords. Going undercover, Mace investigates a web of adversaries that pushes him to the boundaries of the Jedi code." },
    { phase:"Before the Clone Wars", cat:"YA", title:"Queen's Shadow", author:"E. K. Johnston", narrator:"Catherine Taber", pubdate:"March 5, 2019", publisher:"Disney–Lucasfilm Press", timeline:"28 BBY", runtime:"8h 21m", cover:CDN+"0/0e/QueensShadow.png/revision/latest?cb=20190305210550", lead:"Padmé's transition from Queen of Naboo to Senator of the Republic.", summary:"Her reign over, Padmé is asked to become Naboo's representative in the Galactic Senate. Leaving her handmaidens and her old life behind, she must navigate the treacherous world of Coruscant politics — where she draws the attention of dangerous enemies and learns a senator's power is far more fragile than a queen's." },
    { phase:"The Clone Wars", cat:"Audio Drama", title:"Dooku: Jedi Lost", author:"Cavan Scott", narrator:"Full cast", pubdate:"April 30, 2019", publisher:"Random House Audio", timeline:"23 BBY", runtime:"6h 21m", cover:CDN+"c/c3/DookuJediLost.jpg/revision/latest?cb=20190328235713", lead:"An audio-original drama tracing the making of Count Dooku.", summary:"Told as a full-cast performance, the Jedi Asajj Ventress pieces together the history of Count Dooku — from his childhood as an aristocrat of Serenno through his rise as one of the Order's greatest Jedi, and the doubts that would lead him to the dark side." },
    { phase:"The Clone Wars", cat:"Adult", title:"Inquisitor: Rise of the Red Blade", author:"Delilah S. Dawson", narrator:"Kristen Sieh", pubdate:"July 18, 2023", publisher:"Random House Worlds", timeline:"22–14 BBY", runtime:"12h 58m", cover:CDN+"3/32/InquisitorAudiobook.jpg/revision/latest?cb=20221011193149", lead:"The fall of a Jedi and the rise of an Inquisitor.", summary:"Iskat Akaris is a Jedi Knight who has always felt she doesn't belong. As the Clone Wars end and Order 66 shatters the galaxy, her simmering anger makes her the perfect recruit for the Empire's Inquisitorius — hunters of surviving Jedi. A dark study of how a Jedi becomes an agent of the evil she once fought." },
    { phase:"The Clone Wars", cat:"YA", title:"Queen's Hope", author:"E. K. Johnston", narrator:"Catherine Taber", pubdate:"April 5, 2022", publisher:"Disney–Lucasfilm Press", timeline:"22 BBY", runtime:"6h 40m", cover:CDN+"2/25/QueensHopeaudiobook.jpg/revision/latest?cb=20220410030936", lead:"The finale of the Padmé Amidala trilogy, set during the Clone Wars.", summary:"As the Clone Wars erupt, Senator Padmé balances her secret marriage to Anakin with her duty to the Republic. When she's called to a delicate mission, her handmaiden Sabé must once again step into her role as a decoy — testing the bonds of identity, loyalty, and friendship that hold the Queen's circle together." },
    { phase:"The Clone Wars", cat:"Adult", title:"Brotherhood", author:"Mike Chen", narrator:"Jonathan Davis", pubdate:"May 10, 2022", publisher:"Random House Worlds", timeline:"22 BBY", runtime:"12h 46m", cover:CDN+"d/d7/Brotherhood_audiobook_final_cover.png/revision/latest?cb=20221226030429", lead:"Obi-Wan Kenobi and Anakin Skywalker at the dawn of the Clone Wars.", summary:"After a devastating bombing on Cato Neimoidia, Obi-Wan — newly a Master and Council member — is sent alone into a political minefield, while the newly knighted Anakin follows. The mission forces the two to define their partnership as equals for the first time, cementing the brotherhood at the heart of the saga." },
    { phase:"The Clone Wars", cat:"Adult", title:"Catalyst: A Rogue One Novel", author:"James Luceno", narrator:"Jonathan Davis", pubdate:"November 15, 2016", publisher:"Del Rey", timeline:"21–17 BBY", runtime:"11h 15m", cover:CDN+"3/30/Catalyst-Audiobook.jpg/revision/latest?cb=20170311191348", lead:"The prelude to Rogue One — the origins of the Death Star and the Erso family.", summary:"Scientist Galen Erso believes his crystal research could bring limitless energy to the galaxy. His acquaintance Orson Krennic sees a weapon. Spanning the Clone Wars into the early Empire, the novel charts how Krennic manipulates Galen, Lyra, and their daughter Jyn into the orbit of the Death Star project." },
    { phase:"The Clone Wars", cat:"Adult", title:"Thrawn Ascendancy: Chaos Rising", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"September 1, 2020", publisher:"Del Rey", timeline:"19 BBY", runtime:"15h 05m", cover:CDN+"e/e5/Chaos-Rising-Audiobook.jpg/revision/latest?cb=20210202201924", lead:"Before the Empire, Thrawn rises within the Chiss Ascendancy in the Unknown Regions.", summary:"The first Ascendancy novel follows a young Thrawn as he ascends the Chiss Defense Force, confronting a hidden threat massing against his people. Political intrigue and military genius set far from the Republic, revealing the culture that shaped the galaxy's most calculating tactician." },
    { phase:"The Clone Wars", cat:"Adult", title:"Dark Disciple", author:"Christie Golden", narrator:"Marc Thompson", pubdate:"July 7, 2015", publisher:"Del Rey", timeline:"19 BBY", runtime:"11h 11m", cover:CDN+"6/6d/DarkDisciple-Audiobook.jpg/revision/latest?cb=20170719204124", lead:"Based on unproduced Clone Wars episodes — the Jedi sanction an assassination.", summary:"Desperate to end Count Dooku's terror, the Jedi Council authorizes a shocking plan: assassinate him. They task the unconventional Quinlan Vos, who allies with Dooku's former apprentice, the bounty hunter Asajj Ventress. As the two grow close, their mission blurs the line between light and dark." },
    { phase:"The Clone Wars", cat:"Adult", title:"Master of Evil", author:"Adam Christopher", narrator:"Marc Thompson", pubdate:"November 11, 2025", publisher:"Random House Worlds", timeline:"19 BBY", runtime:"15h 27m", cover:CDN+"0/08/MasterOfEvil-AudioCover.png/revision/latest?cb=20250414162943", lead:"A late-Clone-Wars-era tale of the Sith master's schemes.", summary:"Set in the final days of the Clone Wars, the novel follows Darth Sidious and his agents as the Sith's decades-long plan approaches its endgame — a story of manipulation, secrecy, and the dark side's tightening grip. (Publisher summary abbreviated.)" }
  ],

  "reign-of-the-empire": [
    { phase:"The Empire consolidates (19–14 BBY)", cat:"Adult", title:"Reign of the Empire: The Mask of Fear", author:"Alexander Freed", narrator:"January LaVoy", pubdate:"February 25, 2025", publisher:"Random House Worlds", timeline:"19 BBY", runtime:"16h 52m", cover:CDN+"b/be/MaskOfFearAB-Cover.png/revision/latest?cb=20250225104254", lead:"The first days of the Empire, as the Republic's defenders reckon with what they've become.", summary:"In the aftermath of the Clone Wars, Palpatine tightens his grip on an exhausted galaxy. Senators Bail Organa, Mon Mothma, and Saw Gerrera each confront the reality of the new regime — and the impossible choices facing anyone who would resist it — in this launch of a trilogy chronicling the Empire's rise. (Publisher summary abbreviated.)" },
    { phase:"The Empire consolidates (19–14 BBY)", cat:"Adult", title:"Thrawn Ascendancy: Chaos Rising", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"September 1, 2020", publisher:"Del Rey", timeline:"19 BBY", runtime:"15h 05m", cover:CDN+"e/e5/Chaos-Rising-Audiobook.jpg/revision/latest?cb=20210202201924", lead:"Before the Empire, Thrawn rises within the Chiss Ascendancy.", summary:"The first Ascendancy novel follows a young Thrawn as he ascends the Chiss Defense Force, confronting a hidden threat massing against his people. (Placement overlaps the Clone Wars and early Empire.)" },
    { phase:"The Empire consolidates (19–14 BBY)", cat:"Adult", title:"Sanctuary: A Bad Batch Novel", author:"Lamar Giles", narrator:"Marc Thompson", pubdate:"August 5, 2025", publisher:"Random House Worlds", timeline:"18 BBY", runtime:"11h 47m", cover:CDN+"1/16/Sanctuary-Cover.jpg/revision/latest?cb=20250207000237", lead:"A novel following Clone Force 99 in the early days of the Empire.", summary:"The rogue clones of the Bad Batch search for safe harbor in a galaxy now hostile to their kind, as the Empire hunts down the last remnants of the Republic's clone army. Set in the world of the animated series. (Publisher summary abbreviated.)" },
    { phase:"The Empire consolidates (19–14 BBY)", cat:"YA", title:"Ahsoka", author:"E. K. Johnston", narrator:"Ashley Eckstein", pubdate:"October 11, 2016", publisher:"Disney–Lucasfilm Press", timeline:"18 BBY", runtime:"7h 04m", cover:CDN+"d/d3/Ahsoka_novel_cover.png/revision/latest?cb=20160715164545", lead:"What happened to Ahsoka Tano between the Clone Wars and her return as Fulcrum.", summary:"A year after Order 66, Ahsoka is in hiding — a mechanic and pilot under the name 'Ashla.' On the farming moon of Raada she becomes the reluctant leader of a resistance movement, drawing the attention of a Jedi-hunting Inquisitor and of Senator Bail Organa. Narrated by Ahsoka's own screen voice, Ashley Eckstein." },
    { phase:"The Empire consolidates (19–14 BBY)", cat:"Adult", title:"Thrawn Ascendancy: Greater Good", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"April 27, 2021", publisher:"Del Rey", timeline:"18 BBY", runtime:"16h 17m", cover:CDN+"c/c1/Thrawn_Ascendancy_Greater_Good_audiobook_cover.png/revision/latest?cb=20210202202535", lead:"The second Ascendancy novel deepens the Chiss political intrigue.", summary:"As Thrawn's reputation grows, the Chiss Ascendancy faces mounting external threats and internal rivalries among its ruling families. Thrawn must navigate both the battlefield and the treacherous politics of his own people. (Publisher summary abbreviated.)" },
    { phase:"The Empire consolidates (19–14 BBY)", cat:"Adult", title:"Thrawn Ascendancy: Lesser Evil", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"November 16, 2021", publisher:"Del Rey", timeline:"18 BBY", runtime:"23h 13m", cover:CDN+"9/9c/LesserEvilAudio.jpg/revision/latest?cb=20210402212948", lead:"The conclusion of the Ascendancy trilogy.", summary:"Thrawn's choices come to a head as the Chiss Ascendancy confronts its gravest crisis, setting the stage for his eventual exile and the path that will lead him to the Empire. (Publisher summary abbreviated.)" },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"Adult", title:"Thrawn", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"April 11, 2017", publisher:"Del Rey", timeline:"c. 15–2 BBY", runtime:"16h 56m", cover:CDN+"6/63/Thrawn-Audiobook.jpg/revision/latest?cb=20170512162546", lead:"\"I study the art of war. Work to perfect it.\"", summary:"After Thrawn is rescued from exile by Imperial soldiers, his deadly ingenuity captures the attention of Palpatine. He proves as indispensable as he is ambitious, rising through the ranks — even as his renegade methods infuriate superiors. At his side is his aide Eli Vanto; against him, the ruthless administrator Arihnda Pryce." },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"Adult", title:"Lords of the Sith", author:"Paul S. Kemp", narrator:"Jonathan Davis", pubdate:"April 28, 2015", publisher:"Del Rey", timeline:"14 BBY", runtime:"10h 56m", cover:CDN+"6/6b/Lords_of_the_Sith.jpg/revision/latest?cb=20210718053306", lead:"Darth Vader and Emperor Palpatine, stranded and hunted together.", summary:"When a rebel cell on Ryloth downs their shuttle, the Emperor and his apprentice are stranded on a hostile world, hunted by Twi'lek insurgents led by Cham Syndulla. Forced to rely on each other and the dark side, master and apprentice cut a bloody path across the planet." },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"Adult", title:"Tarkin", author:"James Luceno", narrator:"Euan Morton", pubdate:"November 4, 2014", publisher:"Del Rey", timeline:"14 BBY", runtime:"9h 27m", cover:CDN+"1/15/Tarkin-Audiobook.jpg/revision/latest?cb=20150705235040", lead:"The making of the Empire's most feared Grand Moff.", summary:"Wilhuff Tarkin has risen from frontier soldier to one of the Emperor's most trusted enforcers. When rebels sabotage Imperial interests, Tarkin and Darth Vader are paired to hunt them down — a mission that reveals Tarkin's ruthless philosophy of rule by fear and cements his place at the Emperor's side." },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"YA", title:"Most Wanted", author:"Rae Carson", narrator:"Saskia Maarleveld", pubdate:"May 25, 2018", publisher:"Disney–Lucasfilm Press", timeline:"13 BBY", runtime:"7h 55m", cover:CDN+"4/44/MostWanted-Audiobook.jpg/revision/latest?cb=20201011162120", lead:"A young Han and Qi'ra, before Solo.", summary:"On the streets of Corellia, teenage Han and Qi'ra are rival scrumrats clawing their way up the White Worms' criminal ranks. When a job goes wrong, the two are thrown together on the run — a prequel to the film Solo that traces the origins of one of the saga's most fraught relationships." },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"YA", title:"Crimson Climb", author:"E. K. Johnston", narrator:"Olivia Hack", pubdate:"October 10, 2023", publisher:"Disney–Lucasfilm Press", timeline:"13–12 BBY", runtime:"7h 26m", cover:CDN+"3/37/CrimsonClimbAudiobook.jpg/revision/latest?cb=20240508091134", lead:"Qi'ra's story, from the gangs of Corellia to Crimson Dawn.", summary:"After escaping Corellia without Han, Qi'ra falls into the orbit of the criminal syndicate Crimson Dawn. A survival story tracing how a desperate young woman claws her way up through the galaxy's underworld to become the formidable figure seen in Solo. (Publisher summary abbreviated.)" },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"YA", title:"Rebel Rising", author:"Beth Revis", narrator:"Rebecca Soler", pubdate:"May 2, 2017", publisher:"Disney–Lucasfilm Press", timeline:"13–1 BBY", runtime:"9h 53m", cover:CDN+"4/48/Rebel-Rising-audio.jpg/revision/latest?cb=20250305213011", lead:"Jyn Erso's lost years, between Rogue One's prologue and its opening.", summary:"After Saw Gerrera rescues young Jyn Erso, she's raised as a soldier in his partisan cell — learning to fight, to survive, and eventually to go it alone. The novel fills the gap between the girl abandoned in a bunker and the hardened prisoner introduced in Rogue One." },
    { phase:"The Empire tightens its grip (15–1 BBY)", cat:"Adult", title:"Outlaws: Low Red Moon", author:"Mike Chen", narrator:"Rincon / Johnson", pubdate:"February 3, 2026", publisher:"Random House Worlds", timeline:"19 BBY–10 BBY", runtime:"14h 19m", cover:CDN+"6/67/OutlawsLowRedMoon-Audiobook.jpg/revision/latest?cb=20250922234510", lead:"A tie-in to the Star Wars Outlaws video game.", summary:"A story bridging the Clone Wars and the world of the Outlaws game — following a scoundrel through the Empire-era underworld of bounties, syndicates, and double-crosses. (Publisher summary abbreviated.)" }
  ],

  "age-of-rebellion": [
    { phase:"Before A New Hope (3 BBY–0 BBY)", cat:"YA", title:"Lost Stars", author:"Claudia Gray", narrator:"Pierce Cravens", pubdate:"September 4, 2015", publisher:"Disney–Lucasfilm Press", timeline:"6 BBY–5 ABY", runtime:"12h 27m", cover:CDN+"d/d6/LostStars-Audiobook.jpg/revision/latest?cb=20201011161950", lead:"Two childhood friends on opposite sides of the Galactic Civil War.", summary:"Thane Kyrell and Ciena Ree grow up dreaming of flying for the Empire. But as the Rebellion rises and they witness the Empire's atrocities, their loyalties diverge — Thane to the Alliance, Ciena to the Empire. A sweeping romance that spans the entire original trilogy, from before A New Hope to the Battle of Jakku." },
    { phase:"Before A New Hope (3 BBY–0 BBY)", cat:"YA", title:"Leia, Princess of Alderaan", author:"Claudia Gray", narrator:"Saskia Maarleveld", pubdate:"September 1, 2017", publisher:"Disney–Lucasfilm Press", timeline:"3 BBY", runtime:"9h 22m", cover:CDN+"f/f1/Leia-Audiobook.jpg/revision/latest?cb=20201011021030", lead:"A sixteen-year-old Leia Organa, on the cusp of the Rebellion.", summary:"As Leia undertakes the trials that will confirm her as heir to Alderaan's throne, she begins to suspect her parents are hiding something — their quiet involvement in a growing rebellion against the Empire. A coming-of-age story about the princess claiming her place in the fight." },
    { phase:"Before A New Hope (3 BBY–0 BBY)", cat:"Adult", title:"Thrawn: Alliances", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"July 24, 2018", publisher:"Del Rey", timeline:"2 BBY", runtime:"12h 57m", cover:CDN+"5/59/ThrawnAlliances-Audiobook.jpg/revision/latest?cb=20180724183330", lead:"Two of the Emperor's most powerful servants — Thrawn and Darth Vader — thrown together.", summary:"When the Emperor senses a disturbance in the Unknown Regions, he dispatches Thrawn and Darth Vader together to investigate. As their uneasy alliance unfolds, the novel intercuts with a Clone Wars-era mission the two shared as Anakin Skywalker and Thrawn — long before either became who they are now." },
    { phase:"Before A New Hope (3 BBY–0 BBY)", cat:"Adult", title:"Thrawn: Treason", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"July 23, 2019", publisher:"Del Rey", timeline:"1 BBY", runtime:"12h 32m", cover:CDN+"b/b8/ThrawnTreason-Audiobook.jpg/revision/latest?cb=20190819192544", lead:"Thrawn's loyalty is tested as his Chiss past collides with his Imperial present.", summary:"Ordered to defend a critical Imperial project or lose his command, Thrawn confronts a threat from the Unknown Regions — and old allegiances to the Chiss Ascendancy that put him at odds with the Empire he serves. The conclusion of the Imperial-era Thrawn trilogy." },
    { phase:"A New Hope (0 BBY)", cat:"Adult", title:"Rogue One: A Star Wars Story", author:"Alexander Freed", narrator:"Jonathan Davis", pubdate:"December 16, 2016", publisher:"Del Rey", timeline:"1 BBY", runtime:"12h 40m", cover:CDN+"f/f2/RogueOne-Audiobook.jpg/revision/latest?cb=20170309144603", lead:"The official novelization of Rogue One.", summary:"Jyn Erso, a criminal with a fractured past, is recruited by the Rebel Alliance for an impossible mission: steal the plans to the Death Star. A grittier, interiorized retelling of the film that deepens Jyn, Cassian, and the doomed crew of Rogue One." },
    { phase:"A New Hope (0 BBY)", cat:"YA", title:"A New Hope: The Princess, the Scoundrel, and the Farm Boy", author:"Alexandra Bracken", narrator:"Thompson / Soler", pubdate:"September 22, 2015", publisher:"Disney–Lucasfilm Press", timeline:"0 BBY", runtime:"9h 30m", cover:CDN+"2/23/ANHPrincessScoundrelFarmBoy-Audiobook.jpg/revision/latest?cb=20170809232649", lead:"A retelling of A New Hope from three heroes' points of view.", summary:"The events of the first film, told in turn through the eyes of Leia, Han, and Luke — a character-driven young-reader retelling that gets inside the heads of the trio as their paths converge aboard the Death Star." },
    { phase:"A New Hope (0 BBY)", cat:"Adult", title:"Battlefront II: Inferno Squad", author:"Christie Golden", narrator:"Janina Gavankar", pubdate:"July 25, 2017", publisher:"Del Rey", timeline:"0 BBY", runtime:"9h 27m", cover:CDN+"5/52/InfernoSquadAudiobook.jpg/revision/latest?cb=20210211234744", lead:"The Rebellion has heroes. The Empire has Inferno Squad.", summary:"After the destruction of the Death Star, the Empire forms an elite special-forces unit led by Iden Versio. Their mission: infiltrate and eliminate the Dreamers, the extremist remnant of Saw Gerrera's Partisans. A prequel to the Battlefront II game, narrated by Iden's own actor, Janina Gavankar." },
    { phase:"A New Hope (0 BBY)", cat:"Adult", title:"Heir to the Jedi", author:"Kevin Hearne", narrator:"Marc Thompson", pubdate:"March 3, 2015", publisher:"Del Rey", timeline:"0 BBY", runtime:"7h 15m", cover:CDN+"2/25/HeirtotheJedi-Audiobook.jpg/revision/latest?cb=20170608223436", lead:"A rare first-person Luke Skywalker adventure, just after A New Hope.", summary:"Fresh off the destruction of the Death Star and with no Jedi Master to guide him, Luke takes on a covert mission for the Alliance while teaching himself to touch the Force. Told entirely in Luke's first-person voice — a unique intimacy for a Star Wars novel." },
    { phase:"A New Hope (0 BBY)", cat:"Adult", title:"Smuggler's Run", author:"Greg Rucka", narrator:"Marc Thompson", pubdate:"September 4, 2015", publisher:"Disney–Lucasfilm Press", timeline:"0 BBY", runtime:"4h 24m", cover:CDN+"d/dc/Smugglers_Run.png/revision/latest?cb=20150709015644", lead:"A Han Solo and Chewbacca adventure between A New Hope and Empire.", summary:"With a price on his head and the Alliance calling in a favor, Han reluctantly takes one more job — rescuing a rebel agent from an Imperial-occupied world. A fast, pulpy caper that captures Han and Chewie at their roguish best." },
    { phase:"A New Hope (0 BBY)", cat:"Anthology", title:"Doctor Aphra: An Audiobook Original", author:"Sarah Kuhn", narrator:"Full cast", pubdate:"July 21, 2020", publisher:"Random House Audio", timeline:"0 BBY", runtime:"6h 20m", cover:CDN+"f/fa/DoctorAphraAudiobook.jpg/revision/latest?cb=20200722005127", lead:"An audio-original, full-cast dramatization of the fan-favorite rogue archaeologist.", summary:"Adapting the Marvel comic run, this full-cast production follows the amoral archaeologist Chelli Aphra through a galaxy of ancient relics, murder droids, and double-crosses. Produced as an original audio drama rather than a straight reading." },
    { phase:"The Empire Strikes Back & after (3–4 ABY)", cat:"Adult", title:"Battlefront: Twilight Company", author:"Alexander Freed", narrator:"Jonathan Davis", pubdate:"November 3, 2015", publisher:"Del Rey", timeline:"3 ABY", runtime:"12h 30m", cover:CDN+"9/91/Battlefront_Twilight_Company_cover.jpg/revision/latest?cb=20150828172004", lead:"The Galactic Civil War from the mud-level view of the infantry.", summary:"The soldiers of the Rebel Alliance's Sixty-First Mobile Infantry — 'Twilight Company' — grind through a brutal campaign against the Empire. A war novel that trades heroes and Jedi for the exhausted grunts who actually fight the war." },
    { phase:"The Empire Strikes Back & after (3–4 ABY)", cat:"YA", title:"Moving Target", author:"Castellucci & Fry", narrator:"January LaVoy", pubdate:"September 4, 2015", publisher:"Disney–Lucasfilm Press", timeline:"4 ABY", runtime:"4h 06m", cover:CDN+"f/fe/MovingTarget-Audiobook.jpg/revision/latest?cb=20201117122613", lead:"A Princess Leia adventure between Empire and Return of the Jedi.", summary:"With the Rebel fleet in danger, Leia volunteers for a decoy mission to draw Imperial forces away — a gamble that forces her to weigh the lives spent against the lives saved. Framed as Leia recounting the story years later." },
    { phase:"The Empire Strikes Back & after (3–4 ABY)", cat:"Adult", title:"The Princess and the Scoundrel", author:"Beth Revis", narrator:"Maarleveld / Thompson", pubdate:"August 16, 2022", publisher:"Random House Worlds", timeline:"4 ABY", runtime:"11h 06m", cover:CDN+"5/5d/PrincessAndTheScoundrelAudiobook.png/revision/latest?cb=20220514221838", lead:"Han and Leia's honeymoon, days after the Battle of Endor.", summary:"With the Emperor dead and the second Death Star destroyed, Han and Leia marry and take a honeymoon aboard a luxury cruiser — only to find the galaxy's turmoil follows them. A romance that also reckons with what victory actually costs the people who won it." },
    { phase:"The Empire Strikes Back & after (3–4 ABY)", cat:"Adult", title:"Alphabet Squadron", author:"Alexander Freed", narrator:"Saskia Maarleveld", pubdate:"June 11, 2019", publisher:"Del Rey", timeline:"4 ABY", runtime:"13h 51m", cover:CDN+"f/f0/AlphabetSquadron-Audiobook.jpg/revision/latest?cb=20190612211630", lead:"Five damaged pilots in five different starfighters, after the Emperor's death.", summary:"In the chaotic months after Endor, New Republic Captain Yrica Quell — a defector from the Empire — assembles a misfit squadron flying one of each Rebel starfighter type to hunt down an elite Imperial TIE unit. Heavy on the psychology of pilots living with what the war made them." },
    { phase:"The Empire Strikes Back & after (3–4 ABY)", cat:"Anthology", title:"From a Certain Point of View", author:"Various (40 authors)", narrator:"Full cast", pubdate:"October 3, 2017", publisher:"Del Rey", timeline:"0 BBY", runtime:"14h 43m", cover:CDN+"8/85/FromACertainPointOfView-Audiobook.jpg/revision/latest?cb=20211020202311", lead:"A New Hope retold in 40 short stories, each from a background character's view.", summary:"Forty authors each take a minor or background character from A New Hope — a stormtrooper, a cantina alien, a Jawa — and tell that slice of the film from their perspective. A full-cast anthology; companion volumes cover Empire and Return of the Jedi." }
  ],

  "new-republic": [
    { phase:"The Battle of Jakku (4–5 ABY)", cat:"Adult", title:"Aftermath", author:"Chuck Wendig", narrator:"Marc Thompson", pubdate:"September 4, 2015", publisher:"Del Rey", timeline:"4 ABY", runtime:"12h 40m", cover:CDN+"e/ed/Aftermath-Audiobook.jpg/revision/latest?cb=20170622181019", lead:"The Empire didn't die at Endor. The war did not end.", summary:"In the chaos after the Emperor's death, the Empire's remnants regroup for a secret summit on Akiva. A ragtag group — a bounty hunter, an Imperial defector, a rebel pilot, and a teenage tech genius — stumble into the plot. The first of the trilogy bridging Return of the Jedi and The Force Awakens." },
    { phase:"The Battle of Jakku (4–5 ABY)", cat:"Adult", title:"Shadow Fall", author:"Alexander Freed", narrator:"Carol Monda", pubdate:"June 23, 2020", publisher:"Del Rey", timeline:"5 ABY", runtime:"14h 27m", cover:CDN+"7/7b/ShadowFall-Audiobook.png/revision/latest?cb=20200624074259", lead:"The second Alphabet Squadron novel — the hunt turns desperate.", summary:"Alphabet Squadron springs a trap on the elite Imperial TIE unit Shadow Wing, but the mission spirals as Captain Yrica Quell's hidden past threatens to unravel the team. A darker middle chapter about the psychological toll of a war that refuses to end. (Publisher summary abbreviated.)" },
    { phase:"The Battle of Jakku (4–5 ABY)", cat:"Adult", title:"Aftermath: Life Debt", author:"Chuck Wendig", narrator:"Marc Thompson", pubdate:"July 12, 2016", publisher:"Del Rey", timeline:"5 ABY", runtime:"13h 51m", cover:CDN+"6/60/AftermathLifeDebt-Audiobook.jpg/revision/latest?cb=20170719205801", lead:"Han and Chewie join the hunt as the New Republic presses its advantage.", summary:"The second Aftermath novel finds Han Solo and Chewbacca on a mission to liberate Kashyyyk, while Norra Wexley's team pursues the Imperial warlord Rae Sloane. The Empire, cornered, begins to consolidate around a mysterious figure in the Unknown Regions." },
    { phase:"The Battle of Jakku (4–5 ABY)", cat:"Adult", title:"Victory's Price", author:"Alexander Freed", narrator:"January LaVoy", pubdate:"March 2, 2021", publisher:"Del Rey", timeline:"5 ABY", runtime:"16h 06m", cover:CDN+"8/89/VictorysPrice.jpg/revision/latest?cb=20210131075536", lead:"The conclusion of the Alphabet Squadron trilogy.", summary:"As the Galactic Civil War reaches its bloody end at Jakku, Alphabet Squadron makes its final reckoning with Shadow Wing — and with the question of what soldiers owe when the war they were built for is finally over. (Publisher summary abbreviated.)" },
    { phase:"The Battle of Jakku (4–5 ABY)", cat:"Adult", title:"Aftermath: Empire's End", author:"Chuck Wendig", narrator:"Marc Thompson", pubdate:"February 21, 2017", publisher:"Del Rey", timeline:"5 ABY", runtime:"15h 12m", cover:CDN+"2/23/AftermathEmpiresEnd-Audiobook.jpg/revision/latest?cb=20170309145559", lead:"The last stand of the Empire, at the Battle of Jakku.", summary:"Cornered on the desert world of Jakku, the Empire's Grand Admiral Rae Sloane and the shadowy Gallius Rax play out the regime's endgame while the New Republic masses for a final battle. The trilogy's conclusion, culminating in the graveyard of ships glimpsed in The Force Awakens." },
    { phase:"Mercenaries & the New Republic (7–21 ABY)", cat:"Adult", title:"Last Shot", author:"Daniel José Older", narrator:"Thompson / LaVoy", pubdate:"April 17, 2018", publisher:"Del Rey", timeline:"7 ABY", runtime:"10h 55m", cover:CDN+"8/8e/LastShot-Audiobook.jpg/revision/latest?cb=20180418232526", lead:"Han and Lando, across two timelines, chasing one old mistake.", summary:"Years after Endor, a threat rooted in Han and Lando's smuggling pasts resurfaces, forcing the two to reunite. The story cuts between their younger, roguish days and their older, more complicated lives — a caper and a meditation on getting older in a galaxy that keeps needing saving." },
    { phase:"Mercenaries & the New Republic (7–21 ABY)", cat:"YA", title:"Hunters: Battle for the Arena", author:"Mark Oshiro", narrator:"Arina Ii", pubdate:"October 24, 2023", publisher:"Disney–Lucasfilm Press", timeline:"9 ABY", runtime:"5h 30m", cover:CDN+"d/d1/BattleForArenaAudiobook.jpg/revision/latest?cb=20230916210607", lead:"A tie-in to the Star Wars: Hunters game, set in the New Republic era.", summary:"On the fringe world of Vespaara, fighters from across the galaxy gather to compete in the arena of the Grand Arena championship — a middle-grade adventure exploring the mercenaries and misfits drawn to the spectacle. (Publisher summary abbreviated.)" },
    { phase:"Mercenaries & the New Republic (7–21 ABY)", cat:"YA", title:"Poe Dameron: Free Fall", author:"Alex Segura", narrator:"Sean Kenin Elias-Reyes", pubdate:"August 4, 2020", publisher:"Disney–Lucasfilm Press", timeline:"18–19 ABY", runtime:"9h 30m", cover:CDN+"5/59/FreeFall-Audiobook.jpg/revision/latest?cb=20201117122443", lead:"Before the Resistance, a teenage Poe Dameron falls in with a spice-runner gang.", summary:"Restless on his home planet of Yavin 4, a young Poe joins a crew of spice runners led by the enigmatic Zorii — a coming-of-age adventure that fills in the criminal past Poe references in The Rise of Skywalker." },
    { phase:"Mercenaries & the New Republic (7–21 ABY)", cat:"Adult", title:"Shadow of the Sith", author:"Adam Christopher", narrator:"William DeMeritt", pubdate:"June 28, 2022", publisher:"Random House Worlds", timeline:"21 ABY", runtime:"16h 45m", cover:CDN+"2/24/Shadow_of_the_Sith_audiobook_cover.png/revision/latest?cb=20220514220233", lead:"Luke Skywalker and Lando Calrissian hunt a threat from the Sith's shadow.", summary:"Years after the Empire's fall, Luke is drawn into a search prompted by dark visions, while cultists of the Sith Eternal hunt a young girl named Rey on Jakku. A key bridge to the sequel trilogy, connecting Ochi of Bestoon, Rey's parents, and the returning threat of the Sith." }
  ],

  "rise-first-order": [
    { phase:"The New Republic drifts (28–30 ABY)", cat:"Adult", title:"Bloodline", author:"Claudia Gray", narrator:"January LaVoy", pubdate:"May 3, 2016", publisher:"Del Rey", timeline:"28 ABY", runtime:"12h 33m", cover:CDN+"3/36/Bloodline-Audiobook.jpg/revision/latest?cb=20170627223652", lead:"Princess Leia, a generation after Endor, as the New Republic fractures.", summary:"Decades after the Empire's fall, the Senate is paralyzed by feuding Populist and Centrist factions. Senator Leia Organa uncovers a criminal conspiracy — and a secret about her own past threatens to detonate her career. The novel that lays the groundwork for the Resistance and the First Order's rise." },
    { phase:"The New Republic drifts (28–30 ABY)", cat:"Adult", title:"The Perfect Weapon", author:"Delilah S. Dawson", narrator:"January LaVoy", pubdate:"November 24, 2015", publisher:"Del Rey", timeline:"29 ABY", runtime:"2h 05m", cover:CDN+"3/3e/PerfectWeaponAudio.jpg/revision/latest?cb=20210913105604", lead:"A short-story lead-in to The Force Awakens.", summary:"A retired mercenary is pulled back for one last job — a hit that ties into the shadowy forces gathering before The Force Awakens. A quick, sharp novella-length listen introducing a background player from the film." },
    { phase:"The New Republic drifts (28–30 ABY)", cat:"Adult", title:"The Legends of Luke Skywalker", author:"Ken Liu", narrator:"January LaVoy", pubdate:"October 31, 2017", publisher:"Disney–Lucasfilm Press", timeline:"30 ABY", runtime:"6h 47m", cover:CDN+"2/2f/The_Legends_of_Luke_Skywalker_final_cover.jpg/revision/latest?cb=20170720190858", lead:"Six tall tales about a Jedi who has become a myth.", summary:"Aboard a ship bound for Canto Bight, travelers swap wildly different stories about Luke Skywalker — some plausible, some absurd, all revealing how legend outgrows the man. A framing-device anthology about the power of myth in a galaxy that has half-forgotten the Jedi." },
    { phase:"Toward the Resistance (31–33 ABY)", cat:"YA", title:"Before the Awakening", author:"Greg Rucka", narrator:"Elias-Reyes / Brackett / Almasy", pubdate:"December 18, 2015", publisher:"Disney–Lucasfilm Press", timeline:"31 ABY", runtime:"4h 12m", cover:CDN+"5/50/BeforeTheAwakening-Audiobook.jpg/revision/latest?cb=20250805065927", lead:"The lives of Finn, Rey, and Poe just before The Force Awakens.", summary:"Three linked stories: Finn's regimented life as First Order stormtrooper FN-2187, Rey's scavenger survival on Jakku, and Poe's rise as a hotshot Resistance pilot. Character prologues that set up the sequel trilogy's trio." },
    { phase:"Toward the Resistance (31–33 ABY)", cat:"YA", title:"Force Collector", author:"Kevin Shinick", narrator:"Euan Morton", pubdate:"November 19, 2019", publisher:"Disney–Lucasfilm Press", timeline:"32 ABY", runtime:"6h 04m", cover:CDN+"f/f6/ForceCollector-Audio.jpg/revision/latest?cb=20201011020825", lead:"A teenager haunted by visions of the Jedi, in the years before the Resistance.", summary:"Karr Nuq Sin experiences strange visions whenever he touches objects connected to the Force. With a droid and a new friend, he sets out across the galaxy to understand his gift and the vanished Jedi — a road-trip mystery set on the eve of the sequel era." },
    { phase:"Toward the Resistance (31–33 ABY)", cat:"YA", title:"Eyes Like Stars", author:"Ashley Poston", narrator:"Kristen Sieh", pubdate:"October 28, 2025", publisher:"Disney–Lucasfilm Press", timeline:"33 ABY", runtime:"9h 15m", cover:CDN+"8/86/EyesLikeStars-Audiobook-Final.jpg/revision/latest?cb=20260413064744", lead:"A late-New-Republic-era YA adventure on the cusp of the sequel trilogy.", summary:"Set in the years just before The Force Awakens, following young characters navigating a galaxy where the New Republic's complacency is about to be shattered by the First Order. (Publisher summary abbreviated.)" }
  ],

  "new-jedi-order": [
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"Adult", title:"Phasma", author:"Delilah S. Dawson", narrator:"January LaVoy", pubdate:"September 1, 2017", publisher:"Del Rey", timeline:"34 ABY", runtime:"11h 31m", cover:CDN+"3/30/Phasma-Audiobook.jpg/revision/latest?cb=20170910040436", lead:"The origins of the First Order's chrome-armored enforcer.", summary:"A Resistance spy interrogates a captured First Order officer for the truth about Captain Phasma — piecing together her brutal rise from a savage tribal world to the ranks of the First Order. A story about ambition and survival with no loyalty but to herself." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"YA", title:"The Last Jedi: Cobalt Squadron", author:"Elizabeth Wein", narrator:"Kelly Marie Tran", pubdate:"December 15, 2017", publisher:"Disney–Lucasfilm Press", timeline:"34 ABY", runtime:"4h 30m", cover:CDN+"7/78/CobaltSquadronAudiobook.jpg/revision/latest?cb=20200925072252", lead:"Rose and Paige Tico before The Last Jedi, narrated by Rose's own actor.", summary:"Sisters Rose and Paige Tico serve aboard a Resistance bomber in Cobalt Squadron, running relief missions to worlds crushed by the First Order. A lead-in to The Last Jedi, read by Kelly Marie Tran, who plays Rose on screen." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"Adult", title:"The Force Awakens (novelization)", author:"Alan Dean Foster", narrator:"Marc Thompson", pubdate:"December 18, 2015", publisher:"Del Rey", timeline:"34 ABY", runtime:"9h 45m", cover:CDN+"d/de/TheForceAwakens-Audiobook.jpg/revision/latest?cb=20170622175249", lead:"The official novelization of Episode VII.", summary:"Thirty years after the Empire's fall, a scavenger named Rey, a runaway stormtrooper named Finn, and the Resistance pilot Poe are swept into the fight against the First Order and its masked enforcer Kylo Ren. Foster — who ghost-wrote the original 1976 novelization — returns to expand the film with added interiority." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"Adult", title:"Galaxy's Edge: Black Spire", author:"Delilah S. Dawson", narrator:"January LaVoy", pubdate:"August 27, 2019", publisher:"Del Rey", timeline:"34 ABY", runtime:"9h 20m", cover:CDN+"2/21/GalaxysEdge-BlackSpire-Audiobook.jpg/revision/latest?cb=20190908185302", lead:"A Resistance spy on the frontier world of Batuu — home of the theme-park land.", summary:"Vi Moradi, the spy from Phasma, is sent by Leia to the remote Outer Rim world of Batuu to build a secret Resistance base in Black Spire Outpost. A tie-in to the Galaxy's Edge parks, grounding that setting in the sequel-era conflict." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"Adult", title:"The Last Jedi (novelization)", author:"Jason Fry", narrator:"Marc Thompson", pubdate:"March 6, 2018", publisher:"Del Rey", timeline:"34 ABY", runtime:"12h 08m", cover:CDN+"e/e5/TheLastJedi-Audiobook.jpg/revision/latest?cb=20180311222204", lead:"The expanded-edition novelization of Episode VIII.", summary:"Rey seeks out the reclusive Luke Skywalker while the Resistance flees a relentless First Order pursuit. Fry's 'Expanded Edition' adds new scenes and deepens the interior lives of Luke, Rey, Kylo, and Poe beyond what the film could show." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"Adult", title:"Resistance Reborn", author:"Rebecca Roanhorse", narrator:"Marc Thompson", pubdate:"November 5, 2019", publisher:"Del Rey", timeline:"34 ABY", runtime:"10h 30m", cover:CDN+"8/84/Resistance_Reborn_Audiobook_Cover.jpg/revision/latest?cb=20191230120136", lead:"The bridge between The Last Jedi and The Rise of Skywalker.", summary:"After the near-annihilation at Crait, the Resistance is down to a handful of survivors. Poe, Leia, and the others work to rebuild their alliance and rally old friends before the First Order finds them. Fills the gap directly before the final film." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"YA", title:"Spark of the Resistance", author:"Justina Ireland", narrator:"Jessica Almasy", pubdate:"October 1, 2019", publisher:"Disney–Lucasfilm Press", timeline:"34 ABY", runtime:"2h 45m", cover:CDN+"4/42/Spark_of_the_Resistance_audiobook_cover.png/revision/latest?cb=20201011015249", lead:"A middle-grade Rey, Poe, Finn, and BB-8 adventure.", summary:"Rey, Poe, and Finn respond to a distress call from a planet whose peaceful inhabitants are being terrorized by the First Order — a self-contained adventure for younger readers set between the final two films." },
    { phase:"The Force Awakens & The Last Jedi (34 ABY)", cat:"YA", title:"A Crash of Fate", author:"Zoraida Córdova", narrator:"Brittany Pressley", pubdate:"August 27, 2019", publisher:"Disney–Lucasfilm Press", timeline:"34 ABY", runtime:"7h 30m", cover:CDN+"8/8a/ACrashofFate.png/revision/latest?cb=20190808231603", lead:"A young-adult romance set on Batuu's Black Spire Outpost.", summary:"Childhood friends Izzy and Jules reunite years later on Batuu and spend one eventful night navigating smugglers and old feelings amid the bustle of Black Spire Outpost. The YA companion to the Galaxy's Edge setting." },
    { phase:"The Rise of Skywalker (35 ABY)", cat:"Adult", title:"Legacy", author:"Madeleine Roux", narrator:"Saskia Maarleveld", pubdate:"—", publisher:"Random House Worlds", timeline:"34–35 ABY", runtime:"—", cover:CDN+"1/17/Legacy-Cover.png/revision/latest?cb=20251022013452", lead:"A sequel-era tale of the Resistance and the returning Sith threat.", summary:"Set around the final chapter of the Skywalker saga, following characters caught up in the Resistance's last stand and the resurgence of the Sith Eternal. (Publisher summary abbreviated.)" },
    { phase:"The Rise of Skywalker (35 ABY)", cat:"Adult", title:"The Rise of Skywalker (novelization)", author:"Rae Carson", narrator:"Marc Thompson", pubdate:"March 17, 2020", publisher:"Del Rey", timeline:"35 ABY", runtime:"9h 30m", cover:CDN+"5/50/TROSExpanded-Audiobook.jpg/revision/latest?cb=20201117122139", lead:"The expanded-edition novelization of Episode IX.", summary:"With the Emperor returned, Rey confronts her heritage and the final battle for the galaxy at Exegol. Carson's 'Expanded Edition' adds material — including scenes and connective tissue — that clarifies and deepens the film's climactic events." }
  ]
};

const LEGENDS_BOOKS = [
  { phase:"Before the Republic / Old Republic era", cat:"Unabridged", title:"Dawn of the Jedi: Into the Void", author:"Tim Lebbon", narrator:"January LaVoy", pubdate:"May 7, 2013", publisher:"Del Rey", timeline:"25,793 BBY", runtime:"10h 24m", cover:CDN+"b/b0/IntotheVoidAudio.png/revision/latest?cb=20201115183951", lead:"The dawn of the Force-users, twenty-five millennia before the films.", summary:"On the remote world of Tython, the Je'daii Order — precursors to the Jedi — must maintain a delicate balance between light and dark. A young Je'daii named Lanoree Brock hunts a threat that could tear that balance apart. The earliest-set Star Wars story recorded as an audiobook." },
  { phase:"Before the Republic / Old Republic era", cat:"Unabridged", title:"The Old Republic: Revan", author:"Drew Karpyshyn", narrator:"Marc Thompson", pubdate:"November 15, 2011", publisher:"Del Rey", timeline:"3954–3950 BBY", runtime:"10h 52m", cover:CDN+"6/63/TOR-Revan.jpg/revision/latest?cb=20110728211622", lead:"The fate of the legendary Knights of the Old Republic hero.", summary:"Haunted by fragmented memories of his time as a Sith Lord, Revan sets out into the Unknown Regions to confront a threat he can't fully remember — a hidden Sith Emperor amassing power. A direct sequel to the beloved BioWare game." },
  { phase:"Before the Republic / Old Republic era", cat:"Unabridged", title:"The Old Republic: Deceived", author:"Paul S. Kemp", narrator:"Marc Thompson", pubdate:"March 22, 2011", publisher:"Del Rey", timeline:"3653 BBY", runtime:"9h 26m", cover:CDN+"5/59/DeceivedAudiobook.png/revision/latest?cb=20201114173320", lead:"The Sith sack of the Jedi Temple on Coruscant.", summary:"Tying into The Old Republic game's 'Deceived' cinematic, the novel follows the brutal Sith warrior Darth Malgus during the shocking assault on Coruscant — and the Jedi and smuggler whose lives he shatters." },
  { phase:"Before the Republic / Old Republic era", cat:"Unabridged", title:"The Old Republic: Fatal Alliance", author:"Sean Williams", narrator:"Marc Thompson", pubdate:"July 20, 2010", publisher:"Del Rey", timeline:"c. 3643 BBY", runtime:"13h 47m", cover:CDN+"d/d6/FatalAllianceAudio.png/revision/latest?cb=20260130114013", lead:"The first novel of The Old Republic MMO era.", summary:"A disparate group — a Jedi, a smuggler, a trooper, an Imperial agent, and a Sith — are drawn together by a mystery on a remote world, uncovering a threat that could upend the cold war between Republic and Sith Empire." },
  { phase:"Before the Republic / Old Republic era", cat:"Unabridged", title:"The Old Republic: Annihilation", author:"Drew Karpyshyn", narrator:"Marc Thompson", pubdate:"November 13, 2012", publisher:"Del Rey", timeline:"3640 BBY", runtime:"9h 39m", cover:CDN+"a/a3/AnnihilationCover.jpg/revision/latest?cb=20120601025557", lead:"A spy, a smuggler, and a Sith battleship.", summary:"Republic agent Theron Shan and smuggler captain Teff'ith race to stop the Sith Empire's most devastating new warship before it can turn the tide of the war. The final Old Republic game-era novel." },
  { phase:"Before the Republic / Old Republic era", cat:"Unabridged", title:"Red Harvest", author:"Joe Schreiber", narrator:"John Glover", pubdate:"December 28, 2010", publisher:"Del Rey", timeline:"3645 BBY", runtime:"7h 56m", cover:CDN+"a/a3/RedHarvestAudio.png/revision/latest?cb=20201115184003", lead:"Zombies at a Sith academy — a Star Wars horror novel.", summary:"A prequel to Death Troopers: at a Sith academy on a frozen world, a dark experiment unleashes an undead plague. Horror-tinged Star Wars, narrated by John Glover." },
  { phase:"Old Republic era", cat:"Unabridged", title:"Darth Bane: Path of Destruction", author:"Drew Karpyshyn", narrator:"Jonathan Davis", pubdate:"October 30, 2012 (audio)", publisher:"Del Rey", timeline:"1003–1000 BBY", runtime:"12h 16m", cover:CDN+"9/9b/Path-of-destruction.jpg/revision/latest?cb=20070719033113", lead:"The rise of the Sith Lord who created the Rule of Two.", summary:"A miner named Dessel becomes Darth Bane, the last Sith to survive the Order's self-destruction — and the architect of the Rule of Two that decrees only a master and an apprentice may exist. The foundation of Sith philosophy for the next thousand years." },
  { phase:"Old Republic era", cat:"Unabridged", title:"Darth Bane: Rule of Two", author:"Drew Karpyshyn", narrator:"Jonathan Davis", pubdate:"October 30, 2012 (audio)", publisher:"Del Rey", timeline:"1000–990 BBY", runtime:"10h 12m", cover:CDN+"1/13/RuleofTwo.jpg/revision/latest?cb=20081021130617", lead:"Bane takes an apprentice — and tests her ruthlessly.", summary:"Darth Bane trains the young, gifted Zannah as his apprentice, even as she plots the eventual betrayal his own doctrine demands. The middle of the Bane trilogy." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Darth Bane: Dynasty of Evil", author:"Drew Karpyshyn", narrator:"Jonathan Davis", pubdate:"October 30, 2012 (audio)", publisher:"Del Rey", timeline:"980 BBY", runtime:"9h 22m", cover:CDN+"1/1c/Dynasty_of_Evil.jpg/revision/latest?cb=20090418194005", lead:"The final reckoning between Bane and his apprentice.", summary:"As his body fails, Darth Bane seeks a technique for immortality while his apprentice Zannah prepares to seize the mantle. The Bane trilogy's conclusion, testing whether the Rule of Two truly makes the Sith stronger." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Darth Plagueis", author:"James Luceno", narrator:"Daniel Davis", pubdate:"January 10, 2012", publisher:"Del Rey", timeline:"67–32 BBY", runtime:"14h 45m", cover:CDN+"0/05/Darthplagueis-cover.jpg/revision/latest?cb=20110713215940", lead:"The tragedy of Darth Plagueis the Wise — and the making of Palpatine.", summary:"Expanding the legend Palpatine tells in Revenge of the Sith, the novel chronicles the Muun Sith Lord Darth Plagueis, his experiments to cheat death, and his fateful apprenticeship of a young, ambitious Naboo politician named Palpatine — who would one day murder him in his sleep." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Maul: Lockdown", author:"Joe Schreiber", narrator:"Jonathan Davis", pubdate:"January 28, 2014", publisher:"Del Rey", timeline:"33 BBY", runtime:"12h 20m", cover:CDN+"d/dc/MaulLockdownCover.jpg/revision/latest?cb=20130427064638", lead:"Darth Maul undercover in a prison fight-pit.", summary:"Before The Phantom Menace, Sidious sends Maul deep undercover into a brutal prison to broker a deal with a weapons dealer — forcing the silent apprentice to survive a gladiatorial gauntlet without blowing his cover." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Darth Maul: Shadow Hunter", author:"Michael Reaves", narrator:"Sam Witwer", pubdate:"August 2, 2022 (unabridged)", publisher:"Random House Audio", timeline:"32 BBY", runtime:"10h 01m", cover:CDN+"e/ec/DarthMaulShadowHunter.jpg/revision/latest?cb=20200903044856", lead:"Maul hunts a broker who knows too much — narrated by Maul's own screen voice.", summary:"On the eve of The Phantom Menace, an information broker learns of the Sith's return and flees to Coruscant's underworld. Darth Maul is dispatched to silence him. The 2022 unabridged re-recording is narrated by Sam Witwer, the voice of Maul in animation." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Outbound Flight", author:"Timothy Zahn", narrator:"Marc Thompson", pubdate:"December 19, 2023 (unabridged)", publisher:"Random House Audio", timeline:"27 BBY", runtime:"17h 37m", cover:CDN+"c/c7/Outbound_Flight_unabrigded_audiobook_cover.jpg/revision/latest?cb=20231020013534", lead:"The doomed Jedi expedition into the Unknown Regions — and Thrawn's Legends debut.", summary:"Six Jedi Masters lead a grand expedition beyond the galaxy's edge, unaware they're on a collision course with a young Chiss commander named Thrawn. A cornerstone of Zahn's Legends Thrawn saga, newly recorded unabridged by Marc Thompson." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Shatterpoint", author:"Matthew Stover", narrator:"Sullivan Jones", pubdate:"June 15, 2021 (unabridged)", publisher:"Random House Audio", timeline:"22 BBY", runtime:"14h 13m", cover:CDN+"3/32/Shatterpoint_PB.jpg/revision/latest?cb=20070719043622", lead:"Mace Windu returns to his savage homeworld during the Clone Wars.", summary:"When his former Padawan goes missing on the jungle world of Haruun Kal, Mace Windu descends into a brutal guerrilla war on the planet of his birth — a dark meditation on violence and the Jedi, in the vein of Heart of Darkness." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Yoda: Dark Rendezvous", author:"Sean Stewart", narrator:"Jonathan Davis", pubdate:"January 23, 2024 (unabridged)", publisher:"Random House Audio", timeline:"19 BBY", runtime:"11h 27m", cover:CDN+"f/f0/YodaDarkRendezvous.jpg/revision/latest?cb=20200722031323", lead:"Yoda answers a summons from Count Dooku during the Clone Wars.", summary:"When Dooku offers to negotiate peace, Yoda suspects a trap but goes anyway — a chance to reach his fallen former student. A warm, witty, and wise Yoda-centered novel, newly recorded unabridged." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Kenobi", author:"John Jackson Miller", narrator:"Jonathan Davis", pubdate:"August 27, 2013", publisher:"Del Rey", timeline:"19 BBY", runtime:"13h 36m", cover:CDN+"4/47/Kenobi-Hardcover.jpg/revision/latest?cb=20130720183933", lead:"He must stop being Obi-Wan — and learn to live as Ben.", summary:"In his first weeks of exile on Tatooine, the hermit 'Ben' Kenobi tries to keep to himself and watch over the infant Luke from afar. But when a settler community is menaced by Tusken Raiders and a charming neighbor's schemes, he can't stay uninvolved. A Star Wars western told through the eyes of the locals who meet the stranger." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"Dark Lord: The Rise of Darth Vader", author:"James Luceno", narrator:"Marc Thompson", pubdate:"February 4, 2025 (unabridged)", publisher:"Random House Audio", timeline:"19 BBY", runtime:"10h 42m", cover:CDN+"d/dc/The_Dark_Lord_Trilogy.jpg/revision/latest?cb=20080425010540", lead:"The first days of Darth Vader, in the ashes of Order 66.", summary:"Weeks after Revenge of the Sith, a group of surviving Jedi struggle to understand what happened to the Order — as the Emperor's terrifying new enforcer, encased in black armor, hunts them down. Newly recorded unabridged by Marc Thompson." },
  { phase:"Rise of the Empire era", cat:"Unabridged", title:"The Force Unleashed", author:"Sean Williams", narrator:"Marc Thompson", pubdate:"November 5, 2024 (unabridged)", publisher:"Random House Audio", timeline:"3–1 BBY", runtime:"12h 22m", cover:CDN+"b/b6/TFU_novel_new_cover.jpg/revision/latest?cb=20080418182359", lead:"Darth Vader's secret apprentice — the story that helped spark the Rebellion.", summary:"Vader secretly trains a powerful Force-user, Galen Marek ('Starkiller'), to hunt the surviving Jedi — until the apprentice's path unexpectedly helps ignite the Rebel Alliance. The Legends novelization of the hit game, newly recorded unabridged." },
  { phase:"Rebellion era", cat:"Unabridged", title:"Death Troopers", author:"Joe Schreiber", narrator:"Sean Kenin", pubdate:"October 13, 2009", publisher:"Random House Audio", timeline:"1 BBY", runtime:"6h 42m", cover:CDN+"b/b9/DeathTroopers-Audiobook.jpg/revision/latest?cb=20201117113634", lead:"A zombie outbreak aboard an Imperial prison barge.", summary:"When a derelict Star Destroyer infects a prison barge with a horrifying plague, the survivors — including two young brothers, and a cameo by Han and Chewie — must escape a ship full of the undead. The first Star Wars horror novel." },
  { phase:"Old Republic era", cat:"Audio Drama", title:"Tales of the Jedi", author:"John Whitman (adapt.)", narrator:"Full cast", pubdate:"January 1995", publisher:"HighBridge Audio", timeline:"4000 BBY", runtime:"2h 45m", cover:CDN+"4/41/TotJCDCover.jpg/revision/latest?cb=20200703100532", lead:"A 1990s full-cast dramatization of the classic Old Republic comics.", summary:"An audio drama adapting the Tales of the Jedi comics, set four thousand years before the films, following the ancient Jedi and the Sith Wars of the Old Republic. A landmark early Star Wars audio production." },
  { phase:"Rebellion era", cat:"Audio Drama", title:"Star Wars (NPR radio drama)", author:"Brian Daley", narrator:"Full cast", pubdate:"March 1981", publisher:"NPR", timeline:"0 BBY", runtime:"5h 55m", cover:CDN+"2/2e/Sw-radio.jpg/revision/latest?cb=20080914145759", lead:"The legendary 13-episode NPR dramatization of the original film.", summary:"Brian Daley's expansive radio adaptation of A New Hope — with Mark Hamill and Anthony Daniels reprising their roles — fills in scenes the film only implied, from Luke's life on Tatooine to Leia's rebel intrigues. A beloved piece of Star Wars audio history." }
];
BOOKS["legends"] = LEGENDS_BOOKS;
